# Generated by Django 3.1.2 on 2021-04-22 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210422_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_application_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.IntegerField(default=0, verbose_name='Share ID')),
                ('application_name', models.CharField(default=0, max_length=100, verbose_name='Channel name')),
                ('application_description', models.CharField(default=0, max_length=100, verbose_name='Channel Description')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_channel_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.IntegerField(default=0, verbose_name='Share ID')),
                ('channel_name', models.CharField(default=0, max_length=100, verbose_name='Channel name')),
                ('channel_description', models.CharField(default=0, max_length=100, verbose_name='Channel Description')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tbl_channel_mst',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted='N'), fields=('channel_name',), name='unique if channel name not deleted'),
        ),
        migrations.AddConstraint(
            model_name='tbl_application_mst',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted='N'), fields=('application_name',), name='unique if application name not deleted'),
        ),
    ]
