# Generated by Django 3.1.2 on 2021-04-23 05:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210422_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ticket_type_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.IntegerField(default=0, verbose_name='Share ID')),
                ('ticket_name', models.CharField(default=0, max_length=50, verbose_name='Ticket name')),
                ('ticket_description', models.CharField(default=0, max_length=100, verbose_name='Ticket Description')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_application_mst',
            name='priority_ref_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_master', verbose_name='Priority Ref ID'),
        ),
        migrations.AddConstraint(
            model_name='tbl_ticket_type_mst',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted='N'), fields=('ticket_name',), name='unique if ticket name not deleted'),
        ),
    ]
