# Generated by Django 3.1.2 on 2021-05-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_tbl_role_application_details_tbl_role_application_mst'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_sla_details',
            name='availability_percentage',
            field=models.IntegerField(default=0, verbose_name='availability_percentage'),
        ),
        migrations.AddField(
            model_name='tbl_sla_details',
            name='down_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Down Time'),
        ),
    ]
