# Generated by Django 3.1.2 on 2021-05-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20210505_1742'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tbl_role_application_mst',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted='N'), fields=('company_ref_id', 'role_ref_id'), name='tbl_role_application_mst unique if not deleted'),
        ),
    ]
