# Generated by Django 3.1.2 on 2021-05-10 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20210510_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_message_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.IntegerField(default=0, verbose_name='Share ID')),
                ('name', models.CharField(max_length=200, verbose_name='API Name')),
                ('description', models.CharField(default=0, max_length=200, verbose_name='Description')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tbl_message_mst',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted='N'), fields=('name',), name='tbl_message_mst unique if not deleted'),
        ),
    ]
