# Generated by Django 3.1.2 on 2021-05-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20210510_1221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_application_mst',
            new_name='tbl_service_asset_mst',
        ),
    ]
