# Generated by Django 3.1.2 on 2021-05-12 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20210510_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_issue_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.IntegerField(default=0, verbose_name='Share ID')),
                ('impact_on', models.CharField(blank=True, max_length=100, null=True, verbose_name='Impact On')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('form', models.CharField(blank=True, max_length=100, null=True, verbose_name='Form')),
                ('closed_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
                ('assigned_to_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_employee_mst', verbose_name='Assigned To Ref Id')),
                ('company_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_company_mst', verbose_name='Company Ref Id')),
                ('impact_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_master', verbose_name='Impact Type Ref Id')),
                ('priority_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='issue_priority_ref', to='portal.tbl_master', verbose_name='Priority Ref Id')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_user_mst', verbose_name='Reported By')),
                ('service_asset_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_service_asset_mst', verbose_name='Service Asset Ref Id')),
                ('status_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='issue_status_ref', to='portal.tbl_master', verbose_name='Status Ref Id')),
                ('ticket_type_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_ticket_type_mst', verbose_name='Ticket Type Ref Id')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_issue_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('attach_document', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
                ('header_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='initialItemRow', to='portal.tbl_issue_mst', verbose_name='Header Ref ID')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('issue_details_ref_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_issue_details', verbose_name='Issue Details Ref Id')),
                ('issue_mst_ref_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_issue_mst', verbose_name='Issue Mst Ref Id')),
            ],
        ),
    ]
