# Generated by Django 3.1.2 on 2021-05-12 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_file_tbl_issue_details_tbl_issue_mst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_issue_mst',
            name='assigned_to_ref_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_employee_mst', verbose_name='Assigned To Ref Id'),
        ),
    ]
