# Generated by Django 3.0.8 on 2021-05-17 10:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20210517_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name_plural': 'File'},
        ),
        migrations.AlterModelOptions(
            name='tbl_issue_details',
            options={'verbose_name_plural': 'tbl_issue_details'},
        ),
        migrations.AlterModelOptions(
            name='tbl_issue_mst',
            options={'verbose_name_plural': 'tbl_issue_mst'},
        ),
        migrations.RemoveField(
            model_name='tbl_left_panel',
            name='backend_model_name',
        ),
        migrations.AddField(
            model_name='tbl_left_panel',
            name='module_path',
            field=models.CharField(default=0, max_length=500, verbose_name='Module Path'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='address1',
            field=models.CharField(default=0, max_length=30, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='address2',
            field=models.CharField(default=0, max_length=30, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='address3',
            field=models.CharField(default=0, max_length=30, verbose_name='Address Line 3'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='attach_document',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Attach Document'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='bank_account',
            field=models.CharField(blank=True, max_length=35, null=True, validators=[django.core.validators.RegexValidator('^\\d{9,26}$')], verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='cin',
            field=models.CharField(default=0, max_length=21, verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='comments',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='company_name',
            field=models.CharField(max_length=30, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='company_shortname',
            field=models.CharField(default=0, max_length=30, verbose_name='Company Short Name'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='contact_person_mobile_number',
            field=models.CharField(max_length=30, null=True, verbose_name='Contact Person Mobile No.'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='contact_person_name',
            field=models.CharField(default=0, max_length=30, verbose_name='Contact Person Name'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='currency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_currency_mst', verbose_name='Currency Ref Id'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='gst',
            field=models.CharField(default=0, max_length=15, verbose_name='GST No.'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='is_group_company',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Group Company'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='is_holding_company',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Holding Company'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='is_this_branch',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is This Branch?'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='is_this_under_same_management',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is This Under Same Management?'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='pan',
            field=models.CharField(default=0, max_length=15, verbose_name='PAN'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='percentage_holding',
            field=models.FloatField(default=0.0, verbose_name='Percentage Holding'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='pincode',
            field=models.CharField(default=0, max_length=8, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='tan',
            field=models.CharField(default=0, max_length=15, verbose_name='TAN'),
        ),
        migrations.AlterField(
            model_name='tbl_issue_details',
            name='attach_document',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Attach Document'),
        ),
        migrations.AlterField(
            model_name='tbl_left_panel',
            name='child_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Child Code'),
        ),
        migrations.AlterField(
            model_name='tbl_left_panel',
            name='form_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Form Link'),
        ),
        migrations.AlterField(
            model_name='tbl_left_panel',
            name='sub_child_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sub Child Code'),
        ),
        migrations.AlterField(
            model_name='tbl_user_mst',
            name='user_seq_no',
            field=models.CharField(max_length=40, verbose_name='User Seq No'),
        ),
    ]
