# Generated by Django 3.0.8 on 2021-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20210517_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_left_panel',
            name='backend_model_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Back End Model'),
        ),
    ]
