# Generated by Django 3.0.8 on 2021-05-19 09:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_tbl_assign_screen_to_role_mst'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_assign_screen_to_role_mst',
            options={'verbose_name_plural': 'tbl_assign_screen_to_role_mst'},
        ),
        migrations.CreateModel(
            name='tbl_assign_employee_to_roles_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.IntegerField(default=0, verbose_name='Share ID')),
                ('is_it_employee_flag', models.CharField(default='N', max_length=1, verbose_name='Is it Employee Flag')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
                ('assigned_to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_employee_mst', verbose_name='Assigned To Employee')),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_user_mst', verbose_name='Assigned To User')),
                ('company_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_company_mst', verbose_name='Company Ref Id')),
            ],
            options={
                'verbose_name_plural': 'tbl_assign_employee_to_roles_mst',
            },
        ),
    ]
