# Generated by Django 3.0.8 on 2021-05-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_auto_20210519_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_issue_mst',
            name='closed_by',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Closed By'),
        ),
        migrations.AlterField(
            model_name='tbl_issue_mst',
            name='status_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='issue_status_ref', to='portal.tbl_ticket_status_mst', verbose_name='Status Ref Id'),
        ),
    ]
