# Generated by Django 3.0.8 on 2021-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_auto_20210524_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_issue_details',
            name='is_it_original_entry_flag',
            field=models.CharField(default='N', max_length=1, verbose_name='Is it Original Entry Flag'),
        ),
    ]
