# Generated by Django 3.0.8 on 2021-05-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_auto_20210525_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_assign_screen_to_role_mst',
            name='child_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Child Code'),
        ),
        migrations.AlterField(
            model_name='tbl_assign_screen_to_role_mst',
            name='parent_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Code'),
        ),
        migrations.AlterField(
            model_name='tbl_assign_screen_to_role_mst',
            name='sub_child_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub Child Code'),
        ),
    ]
