# Generated by Django 3.0.8 on 2021-05-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_auto_20210528_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_assign_roles_to_enduser_mst',
            name='is_it_employee_flag',
        ),
        migrations.AddField(
            model_name='tbl_workflow_details',
            name='level_details_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Level Name'),
        ),
        migrations.AlterField(
            model_name='tbl_assign_screen_to_role_mst',
            name='form_ref_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_left_panel', verbose_name='Form Ref Id'),
        ),
    ]
