# Generated by Django 3.0.8 on 2021-06-01 04:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_auto_20210528_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_workflow_activity',
            name='assigned_role',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Assigned Role'),
        ),
        migrations.CreateModel(
            name='tbl_company_priority_link_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.IntegerField(default=0, verbose_name='Share ID')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('revision_status', models.CharField(max_length=20, verbose_name='Revision Status')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
                ('company_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_company_mst', verbose_name='Company Ref Id')),
            ],
            options={
                'verbose_name_plural': 'tbl_company_priority_link_mst',
            },
        ),
        migrations.CreateModel(
            name='tbl_company_priority_link_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Response Time')),
                ('resolution_time', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Resolution Time')),
                ('availability_percentage', models.IntegerField(default=0, verbose_name='availability_percentage')),
                ('down_time', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Down Time')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
                ('header_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='initialItemRow', to='portal.tbl_company_priority_link_mst', verbose_name='Header Ref ID')),
                ('priority_ref_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_master', verbose_name='Priority Ref ID')),
            ],
            options={
                'verbose_name_plural': 'tbl_company_priority_link_details',
            },
        ),
    ]
