# Generated by Django 3.0.8 on 2021-06-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_auto_20210601_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_workflow_routing_details',
            options={'verbose_name_plural': 'tbl_workflow_routing_details'},
        ),
        migrations.AddField(
            model_name='tbl_workflow_activity',
            name='screen_name',
            field=models.CharField(default='SCREEN NAME', max_length=30, verbose_name='Screen Name'),
        ),
    ]
