# Generated by Django 3.0.8 on 2021-06-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_auto_20210612_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_workflow_mst',
            name='service_asset_ref_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_service_asset_mst', verbose_name='Service Asset Ref Id'),
        ),
    ]
