# Generated by Django 3.1.2 on 2021-07-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_auto_20210615_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_company_mst',
            name='cin',
            field=models.CharField(blank=True, default=0, max_length=21, null=True, verbose_name='CIN'),
        ),
    ]
