# Generated by Django 3.0.8 on 2021-08-02 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_tbl_problem_issue_details_tbl_problem_issue_mst'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_asset_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_no', models.CharField(max_length=20, verbose_name='Asset No')),
                ('asset_tag', models.CharField(max_length=20, verbose_name='Asset Tag')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
            ],
            options={
                'verbose_name_plural': 'tbl_asset_details',
            },
        ),
        migrations.CreateModel(
            name='tbl_asset_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.IntegerField(default=0, verbose_name='Share ID')),
                ('asset_type', models.CharField(max_length=200, verbose_name='Asset Type')),
                ('asset_description', models.CharField(default=0, max_length=200, verbose_name='Asset Description')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
            ],
            options={
                'verbose_name_plural': 'tbl_asset_mst',
            },
        ),
        migrations.AddField(
            model_name='tbl_issue_mst',
            name='conversion_ticket_type_ref_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_ticket', to='portal.tbl_ticket_type_mst', verbose_name='C Ticket Type Ref Id'),
        ),
        migrations.AddField(
            model_name='tbl_issue_mst',
            name='converted_issue_ref_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Converted Issue Ref Id'),
        ),
        migrations.AddField(
            model_name='tbl_issue_mst',
            name='converted_problem_ref_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.tbl_problem_issue_mst', verbose_name='Problem Ref ID'),
        ),
        migrations.AddField(
            model_name='tbl_issue_mst',
            name='is_converted_flag',
            field=models.CharField(default='N', max_length=1, verbose_name='Is Converted Flag'),
        ),
        migrations.AddField(
            model_name='tbl_issue_mst',
            name='total_resolution_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Resolution Time'),
        ),
        migrations.AddField(
            model_name='tbl_problem_issue_mst',
            name='total_resolution_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Resolution Time'),
        ),
        migrations.AddField(
            model_name='tbl_sla_details',
            name='escalation_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Escalation Time'),
        ),
        migrations.AddField(
            model_name='tbl_sla_details',
            name='priority_ref_id',
            field=models.ForeignKey(default=65, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_master', verbose_name='Priority Ref ID'),
        ),
        migrations.AddField(
            model_name='tbl_workflow_activity',
            name='actual_resolution_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Actual Resolution Time'),
        ),
        migrations.AddField(
            model_name='tbl_workflow_activity',
            name='end_date_time',
            field=models.DateTimeField(null=True, verbose_name='End Date Time'),
        ),
        migrations.AddField(
            model_name='tbl_workflow_activity',
            name='escalation_date_time',
            field=models.DateTimeField(null=True, verbose_name='Escalation Date Time'),
        ),
        migrations.AddField(
            model_name='tbl_workflow_activity',
            name='start_date_time',
            field=models.DateTimeField(null=True, verbose_name='Start Date Time'),
        ),
        migrations.AlterField(
            model_name='tbl_workflow_mst',
            name='resolution_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Resolution Time'),
        ),
        migrations.AlterField(
            model_name='tbl_workflow_sub_details',
            name='sla_response_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Response Time'),
        ),
        migrations.AddConstraint(
            model_name='tbl_asset_mst',
            constraint=models.UniqueConstraint(condition=models.Q(is_deleted='N'), fields=('asset_type',), name='asset type unique if not deleted'),
        ),
        migrations.AddField(
            model_name='tbl_asset_details',
            name='asset_custodian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodian', to='portal.tbl_employee_mst', verbose_name='Asset Custodian'),
        ),
        migrations.AddField(
            model_name='tbl_asset_details',
            name='asset_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_company_mst', verbose_name='Asset Owner'),
        ),
        migrations.AddField(
            model_name='tbl_asset_details',
            name='header_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='initialItemRow', to='portal.tbl_asset_mst', verbose_name='Header Ref ID'),
        ),
        migrations.AddField(
            model_name='tbl_asset_details',
            name='location_ref_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_location_mst', verbose_name='Location Ref ID'),
        ),
        migrations.AddField(
            model_name='tbl_service_asset_mst',
            name='asset_ref_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_asset_mst', verbose_name='Asset Ref ID'),
        ),
    ]
