# Generated by Django 3.0.8 on 2021-08-10 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_auto_20210802_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_company_mst',
            name='is_company',
            field=models.CharField(default='N', max_length=1, verbose_name='Is Company'),
        ),
        migrations.AlterField(
            model_name='tbl_issue_mst',
            name='conversion_ticket_type_ref_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_tickect', to='portal.tbl_ticket_type_mst', verbose_name='C Ticket Type Ref Id'),
        ),
        migrations.CreateModel(
            name='tbl_entity_relationship_mst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.IntegerField(default=0, verbose_name='Share ID')),
                ('entity_ref_id', models.TextField(default=0, verbose_name='Entity Ref ID')),
                ('is_active', models.CharField(default='Y', max_length=1, verbose_name='Is Active')),
                ('is_deleted', models.CharField(default='N', max_length=1, verbose_name='Is Deleted')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Created Date Time')),
                ('created_by', models.IntegerField(default=0, verbose_name='Created By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Updated Date Time')),
                ('updated_by', models.IntegerField(default=0, verbose_name='Updated By')),
                ('sub_application_id', models.CharField(max_length=20, verbose_name='Sub-Application ID')),
                ('application_id', models.CharField(max_length=20, verbose_name='Application ID')),
                ('company_ref_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portal.tbl_company_mst', verbose_name='Company Ref Id')),
            ],
        ),
    ]
