# Generated by Django 3.0.8 on 2021-08-25 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_auto_20210810_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_company_priority_link_details',
            name='escalation_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Escalation Time'),
        ),
        migrations.AlterField(
            model_name='tbl_issue_mst',
            name='conversion_ticket_type_ref_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_ticket', to='portal.tbl_ticket_type_mst', verbose_name='C Ticket Type Ref Id'),
        ),
    ]
