from django.contrib import admin
from .models import *

# Register your models here.

admin.site.register(tbl_login_mst)
admin.site.register(tbl_role_mst)
admin.site.register(tbl_country_mst)    
admin.site.register(tbl_state_mst)
admin.site.register(tbl_city_mst)
admin.site.register(tbl_location_mst)
admin.site.register(tbl_currency_mst)
admin.site.register(tbl_reason_mst)
admin.site.register(tbl_company_mst)
admin.site.register(tbl_company_contact_details)
admin.site.register(tbl_master)
admin.site.register(tbl_calendar_mst)
admin.site.register(tbl_calendar_details)
admin.site.register(tbl_term_mst)
admin.site.register(tbl_employee_mst)
admin.site.register(tbl_user_mst)
admin.site.register(tbl_channel_mst)
admin.site.register(tbl_service_asset_mst)
admin.site.register(tbl_ticket_type_mst)
admin.site.register(tbl_message_mst)
admin.site.register(tbl_company_application_link_mst)
admin.site.register(tbl_company_application_link_details)
admin.site.register(tbl_ticket_status_mst)
admin.site.register(tbl_sla_mst)
admin.site.register(tbl_sla_details)
admin.site.register(tbl_role_application_mst)
admin.site.register(tbl_role_application_details)
admin.site.register(tbl_workflow_activity_mst)
admin.site.register(tbl_workflow_action_mst)
admin.site.register(tbl_workflow_routing_mst)
admin.site.register(tbl_workflow_routing_details)
admin.site.register(tbl_workflow_level_data_mst)
admin.site.register(tbl_workflow_level_data_details)
admin.site.register(tbl_workflow_mst)
admin.site.register(tbl_workflow_details)
admin.site.register(tbl_workflow_sub_details)
""" admin.site.register(tbl_workflow_activity)
admin.site.register(tbl_workflow_activity_notification_details)
admin.site.register(tbl_workflow_activity_notification_log)
admin.site.register(tbl_workflow_routing_activity) """
admin.site.register(File)
admin.site.register(tbl_issue_mst)
admin.site.register(tbl_issue_details)
""" admin.site.register(tbl_helpdesk_mst)
admin.site.register(tbl_helpdesk_details)
admin.site.register(tbl_assignees_action_mst)
admin.site.register(tbl_assignees_action_details) """
admin.site.register(tbl_left_panel)
admin.site.register(tbl_assign_screen_to_role_mst)
admin.site.register(tbl_assign_roles_to_enduser_mst)
admin.site.register(tbl_assign_roles_to_enduser_details)



